# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KIND
email: hey@whatkind.no
description: I will help your company getting rid of bad design prosess.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: blog/:year/:month/:title/
url: "http://www.whatkind.no" # the base hostname & protocol for your site
imgurl: /img

# Build settings
markdown: kramdown

# Exclude folders on build
exclude: [bower_components]

sass:
  sass_dir: _sass
  style: compressed